language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - TEST_COMMAND="composer test"
        - SYMFONY_PHPUNIT_VERSION="8.5"

matrix:
    fast_finish: true
    include:
          # Test with lowest dependencies
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

          # Test the latest stable release
        - php: 7.2
        - php: 7.3
          env: COVERAGE=true TEST_COMMAND="composer test-ci" DEPENDENCIES="longitude-one/neo4j-php-ogm:^1.0@rc"

          # Force maintained versions of Symfony
        - php: 7.3
          env: SYMFONY_REQUIRE="4.4.*"
        - php: 7.3
          env: SYMFONY_REQUIRE="5.0.*"
        - php: 7.3
          env: SYMFONY_REQUIRE="5.1.*"
        - php: 7.4
          env: SYMFONY_REQUIRE="5.1.*"

          # Latest commit to master
        - php: 7.4
          env: STABILITY="dev" #allowed to fail.

    allow_failures:
        # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi

after_script:
    - wget http://tnyholm.se/reporter.phar
    - php reporter.phar build:upload
